<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Version>0.1.11-alpha4</Version>
  </PropertyGroup>
  <!-- Testing Properties -->
  <PropertyGroup>
    <PlaywrightPlatform Condition="'$(PlaywrightPlatform)' == ''">none</PlaywrightPlatform>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <TestingExtensionsProfile>None</TestingExtensionsProfile>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SiteGen.Tests"></InternalsVisibleTo>
  </ItemGroup>
  <ItemGroup>
    <Using Include="SiteGen.Core.Extensions" />
  </ItemGroup>
</Project>