name: Release to NuGet.org

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Package
        id: run-package
        run: |
            dotnet pack -o ./publish /p:Version=${{ github.ref_name }}

      - name: Attest packages
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: './publish/*.nupkg'

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          path: ./publish/*.nupkg
          
      - name: Attest artifacts
        uses: actions/attest-build-provenance@v2
        with:
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}
          subject-name: ${{ github.repository }}-${{ github.ref_name }}

      - name: Push to NuGet.org
        id: run-push
        run: |
           dotnet nuget push "./publish/*.nupkg" --skip-duplicate --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json
